apiVersion: apps/v1
kind: Deployment
metadata:
  name: erda-etcd
  namespace: {{ .Values.namespace | default "erda-system" }}
  labels:
    app: erda-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erda-etcd
  template:
    metadata:
      labels:
        app: erda-etcd
    spec:
      containers:
      - name: erda-etcd
        image: registry.cn-hangzhou.aliyuncs.com/dice-third-party/etcd:3.3.15-0
        imagePullPolicy: IfNotPresent
        command:
        - etcd
        - --enable-pprof=true
        - --advertise-client-urls=https://erda-etcd.{{ .Values.namespace | default "erda-system" }}.svc.cluster.local:2379
        - --data-dir=/var/lib/etcd
        - --initial-advertise-peer-urls=https://erda-etcd.{{ .Values.namespace | default "erda-system" }}.svc.cluster.local:2380
        - --initial-cluster=erda-etcd=https://erda-etcd.{{ .Values.namespace | default "erda-system" }}.svc.cluster.local:2380
        - --listen-client-urls=https://0.0.0.0:2379
        - --listen-metrics-urls=https://0.0.0.0:2381
        - --listen-peer-urls=https://0.0.0.0:2380
        - --name=erda-etcd
        - --snapshot-count=10000
        - --auto-compaction-retention=1
        - --quota-backend-bytes=8589934592
        - --client-cert-auth=true
        - --trusted-ca-file=/etc/kubernetes/ssl/etcd-ca.pem
        - --cert-file=/etc/kubernetes/ssl/etcd-server.pem
        - --key-file=/etc/kubernetes/ssl/etcd-server-key.pem
        - --peer-client-cert-auth=true
        - --peer-trusted-ca-file=/etc/kubernetes/ssl/etcd-ca.pem
        - --peer-cert-file=/etc/kubernetes/ssl/etcd-peer.pem
        - --peer-key-file=/etc/kubernetes/ssl/etcd-peer-key.pem
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - name: etcd-server-peer-secret
          mountPath: /etc/kubernetes/ssl/
          readOnly: true
      volumes:
      - name: etcd-server-peer-secret
        secret:
          secretName: etcd-server-peer-secret
