apiVersion: v1
kind: Service
metadata:
  name: erda-etcd
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  ports:
  - name: etcd-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: erda-etcd
