---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netportal
  name: netportal
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netportal
  template:
    metadata:
      labels:
        app: netportal
      name: netportal
    spec:
      tolerations:
      - operator: Exists
      containers:
      - env:
        - name: DICE_COMPONENT
          value: netportal
        image: registry.cn-hangzhou.aliyuncs.com/dice-third-party/netportal:1.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 20
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 10
        name: netportal
        readinessProbe:
          failureThreshold: 20
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 512Gi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/netportal-central
          name: netportal-central
          readOnly: true
      volumes:
      - name: netportal-central
        secret:
          defaultMode: 420
          secretName: netportal-central
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: aliyun-registry
---
apiVersion: v1
kind: Service
metadata:
  name: netportal
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: netportal
  type: ClusterIP
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6RENDQWJTZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFYTVJVd0V3WURWUVFEREF4dVpYUncKYjNKMFlXd3RZMkV3SGhjTk1qRXdOREkxTVRBeE1qRTJXaGNOTXpFd05ESXpNVEF4TWpFMldqQVhNUlV3RXdZRApWUVFEREF4dVpYUndiM0owWVd3dFkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRRFo4aTEwVUZKVHhBREoydmFhQzJRTEJXengwVWhjMTZOci8xZ0gzRm1sb3M3QldGcC95d2VCUDZEY3hnejgKRmFkZ3JrK0ZmZGRVYkkvN09lL2lsU2Fzc1htMXJTU0tRRUNnVkxPbkx0SkkvVHI2ZEZ5VmdYMDlmOHQzQ1hLMQpabWVzVzRjaXo5ckkySlg0SWZXdGp2MWprT3dDcktaSkdYLzdaZTZ0QVp2UW5iMUlQY2taQUdlZmZyZXNjcUZHClY4ekZvSjRNb2JVV0h4TGlqcGFFcmJaTXk0Ry80TUdHN1AwS1J6VW9LYnlpYjhJTjg3Qnp6ZVlMbEYreFUwckwKd0JjS0JjajY4STlqVzlTY2RXY2lKL0hCbitBNWxuV2FTbkl1WVZ3SXdkVzZVZkYvUTVrTkRBQ0hrNW9YQktRNQpOeU43cHF3QTNWSEdTb1FvdzU1TFQ3WVpBZ01CQUFHakl6QWhNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEClZSMFBBUUgvQkFRREFnS2tNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFRaHZKR1AvL3BlRTJKTE9WeFdZd1oKeHdjV0c0WXdRNEtrQmFRUVl6OXlHMnQrOWlBT0doWFgydXVKYkEwWDdxRzZPS2N2MDBnbXdUK25zS1VWNzMrRwprYnpmcG1oUnZPQ2x3Sks4aktjY0Z6Z0UwdnUwcGh4anFKR0grRk83NUdIOVdWbms1bDNJSUxPbEVBNm1Eb2ZaClNVd2tEVXJkTWpENGtScE1HQUYrb3MwME4rRkdaaHpHVlFiSWtCSVljK2VRbmpmVjZnczJUVEg2ekVMam1ISVkKTjBVd2oveENjZlBzN0VxZ1ZhTnBqNHg4eHBEcXArQ2lIbENNLzMvSGloMFg1SFpzcmdZSjhaOUJ0M2poZTV0UApld2I5MnNyTkl5L1hpQ2tkblpNZnNDVWtENlpCL1cxN1cxM3FEV09UVy9Yc3RBZXI5QnE0d1RETVc1OHhwdnZnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNtZ0F3SUJBZ0lKQUxuZWlSbnhTS0I4TUEwR0NTcUdTSWIzRFFFQkJRVUFNQmN4RlRBVEJnTlYKQkFNTURHNWxkSEJ2Y25SaGJDMWpZVEFlRncweU1UQTBNalV4TURFeU1UWmFGdzB6TVRBME1qTXhNREV5TVRaYQpNQ0F4SGpBY0JnTlZCQU1NRlc1bGRIQnZjblJoYkM1MFpYSnRhVzUxY3k1cGJ6Q0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMMlF3eHBkb0lDSzdzZlZXTHVXeXFoUXlteFZWemFVWXhhY1JkVHUKTi9hWWJyMUpVV0VkanVtMkpGMzVsYndueGxMZVZ1L2lRY0V1YnpVNEtDMzlIS3ZpZmZNbkpsekxXUDVlTGJseAp5cGgxYWVqSFJnNGxsSDdNYUdRL1ZXbTFvbTdmN25wRHp3ZmsvQjUrek9Vc0VJZk5CT1lPczljZm5vdWZPaGRECmd0RWRuTVg0TmNQU252OHFVNTdHbE5NUWhUeTBKNi9RaUxVNGprYm1Wb1R6L1FsWi9meWFML3dQN1FjVDZFYVoKS1Z6S1orUjZySnVZRzJTMEZyMWNVdmpQWGZYMjNNT1hwK01YbDVVbTlCTDB5MmhKUzAxaEVuMlBLODZKZnRBQwozQ3kxSXVTYTRvV0RjUkJ2RUlDdzhPM2wxTHQ3aGIvR0p4bytueXpFbTJiYjYxc0NBd0VBQWFNbk1DVXdEZ1lEClZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01DTUEwR0NTcUdTSWIzRFFFQkJRVUEKQTRJQkFRQ2dITHdGZjVRZ3lFMHZhTUpsNjhuS081M01oWnc3QjlqTVR4QkdCVWlVait4YU9xT2k3N1J6RUNobgpLQjZ5bXNJR0haeXArUkxqcXJHK1FYTHNJbGtSc0ZMeU0yemttcU45akkxT0tkUEpkWjhqWDhnakh0b0pmNm81CnE2N0FhaHg2c2tIQWdiMHVyUWlnSWNmYXFkZC82dXN3YXhMdlk3QjRmenZmcGF5dFkycDBXQzJTc0oxRytJcVcKQ1B6Mmc3TXgzZzlGS1RQOWpNYWJ2VFZWcjJsQzMrdTlSUlNVMWppeWx6OGJSS0piMnhTVnI4bWs2VjB5Nmc0MQpzbXpPTEVzRGk2WXEweEZuUmJoQ25MbXlJRnQ2RDBmZG1GWnF6TWYzOUM1dExIbXVzbDE5TUozUFBFemZ5TDhVCkE4WWNCcXc5cjMwTHJaTkMzUzZxUy95ek1iN0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  client.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdlpEREdsMmdnSXJ1eDlWWXU1YktxRkRLYkZWWE5wUmpGcHhGMU80MzlwaHV2VWxSCllSMk82YllrWGZtVnZDZkdVdDVXNytKQndTNXZOVGdvTGYwY3ErSjk4eWNtWE10WS9sNHR1WEhLbUhWcDZNZEcKRGlXVWZzeG9aRDlWYWJXaWJ0L3Vla1BQQitUOEhuN001U3dRaDgwRTVnNnoxeCtlaTU4NkYwT0MwUjJjeGZnMQp3OUtlL3lwVG5zYVUweENGUExRbnI5Q0l0VGlPUnVaV2hQUDlDVm45L0pvdi9BL3RCeFBvUnBrcFhNcG41SHFzCm01Z2JaTFFXdlZ4UytNOWQ5ZmJjdzVlbjR4ZVhsU2IwRXZUTGFFbExUV0VTZlk4cnpvbCswQUxjTExVaTVKcmkKaFlOeEVHOFFnTER3N2VYVXUzdUZ2OFluR2o2ZkxNU2JadHZyV3dJREFRQUJBb0lCQUhleHdVK1RrTFc1Zy80UAorMEF2ZlhUNzFtVERHaGR2YUlXdFZQYVhHQ1VQcU5UQ1I2MC9nYTZXZ0s0SjJ2NzhTbUNtM1ZRSWxDWkxrSktWCkMrSEY4V1dpMUk1RXlSZE1tcnU2Y2JxblhCb2FBUzZuTE5mZjZMeUxpdHJKbHIveG5VZlBBNENWOGxKMHhyRG0KdGE5NnZGRlRKZVd4b09LVHA0TlhuZEYwb2xRdy9Ib2lyQ1BRc1Axb003V2xjempqTEZVVGRtam9GL3BhMVB2cQpzbHZHS0N0WG5pelUwN0RkaURpVWJnZ0xrTkxRMzQ0VFJtcGxMMU1jd0RBYk9YdjNWbnhRQng4RzAxTXo2OTVsCk5mK25VaVlxc3RRYjhYN1lhcjhFOGM2RnVMU0lSYWQ4dys2a0JaRUhVdGV3TEwwZG1FNTZPdG9Rdno4d1dMRnQKUS8wZ3l2RUNnWUVBN2RjK09SRHFTQVMxcWsxR1dRc1N3TlVpdjZ3NnM4cWNEeWVrak1yNWNPSVVidzVJVzVrWgpHVHJ1dktpTFdCd0NCZGtkdFRsbExiaUUxbGVQcmIxamkzZ0NJQmRmSm8vai9uaUpIQXo0RjNjT0Y5ejE0RmRxClc1ZHNSN2lOQWxFZ3B3UktmMEp3Mk9EbGl0VFluTk9vdmtlNmRhbEErQ2JyMGtoZTA3dFYvTk1DZ1lFQXpBbnkKSUlvNGQ2ZUUrdjRKL0xvcGhiam03SjRVNkZVMFU5L2F1aERWTUNWZUcrZDNEL3R5RGRHeVVtOG9Ra255V3dMQQpzY25aUFZDTkNyczh4dGQ3RXp3cENscnVlNGpLL2RmY096eFo4aHpkYnZqaFRBY3dBZEMweFdOK2lxQnpUaFJtCnFaU1k5TGN2OStwcnBpNmFMQXhwdUpST0RlakVCL0ZpRS9JeElsa0NnWUVBbGlTM0p4ZENqc3hLVW9RTjBOQm8KdWtyU2NPV3MrU3NDY1o2NUJoaHNkNUtCQzhxY2F4YXUvWHB5azY1aXFQQ2xaa08xdVYzT1BacXFZUlZOb29SWQpmd2IzY0lMUWttdHJwbzA1SVBnZTlkRTJtR0hvNWdMSkphRGx2akVHODF0N25YUGNBNUpSNHRlMmtIbmxkTHM1ClgwV3dzKzV4RVRhZzBGTFhhaHB0SWZrQ2dZQXVIOFZ6WTZ1V0tQRmZ4OU84Sk4xRUZHTm5jK2pvQ0hMV3p4RGoKNVBBOGZRWUVLdFA0Y2UvN2ZiN2c4YTNaSmx3NkJLcEl4b2RzVyt3MlU5Tk9ZK0czbkc3dW4xV3Y2V0Z4OXIwYgpTdTVPVkFZZWt2WmpPSEM2eUZKRkdOTy9STHdzRjJLSnpVU3lkVUxMdVZ0eWFyQ0JhcUR2ajk4Qk4vQXdsM21EClpzbUNxUUtCZ0M2bnUwckE3OEZJc1JjbGszWUIwWHEwditJbXZMOXBXb29TSENMdW94aHZLT29xcWhaSDVmak8KUDdOT3dYVC81bUdJa080UVovVG1McDhRdHh5cCsraUliYmMwNGh6WGZ4TlN5clF5Zk1uMEZDTWZrQ1dCL0xrVgp4NjJNZUlMTUxpc2VVVWphNzlXSm4rU3pEdVhUY0xOaFNrTW9CMjhtQ3VQOThuWlNLc1k5Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: netportal-central
  namespace: {{ .Values.namespace | default "erda-system" }}
type: Opaque
