imagePullSecrets: [ name: aliyun-registry ]

namespace: default

image:
  repository: registry.cn-hangzhou.aliyuncs.com/dice-third-party
  imagePullPolicy: IfNotPresent
 
erda:
  erda:
  erda-ui:
  uc:
  spotAnalyzer:
  spotTelegraf:
  spotFilebeat:
  tmc:
  hepa:
  spotMonitor:
  elf:
  meshController:

