apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.redisFailover.name | default "addon-redis" }}-auth
  namespace: {{ .Values.global.namespace | default "erda-system" }}
data:
  password: {{ .Values.redisFailover.secret }}

