kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-{{ .Values.name | default "addon-registry" }}-pvc
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.storageClass | default "erda-local-volume" }}
