apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.erda.operator.name | default "erda-operator" }}
  name: {{ .Values.erda.operator.name | default "erda-operator" }}
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.erda.operator.name | default "erda-operator" }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.erda.operator.name | default "erda-operator" }}
    spec:
      serviceAccountName: {{ .Values.erda.operator.name | default "erda-operator" }}
      containers:
      - image: {{ .Values.global.image.repository }}/{{ .Values.erda.operator.name | default "erda-operator" }}:{{ .Values.erda.operator.version }}
        imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
        name: {{ .Values.erda.operator.name | default "erda-operator" }}
        env:
        - name: ENABLE_AFFINITY
          value: disable
        - name: ERDA_CLUSTER_INFO
          value: dice-cluster-info
        - name: ERDA_ADDON_INFO
          value: dice-addons-info
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 10Mi
      restartPolicy: Always
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - operator: Exists
