apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearchOperator.name | default "elasticsearch-operator" }}
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: {{ .Values.elasticsearchOperator.name | default "elasticsearch-operator" }}