apiVersion: v1
data:
  etcd-ca.pem: ${ETCD_CA}
  etcd-server-key.pem:  ${ETCD_SERVER_KEY}
  etcd-server.pem: ${ETCD_SERVER}
  etcd-peer-key.pem: ${ETCD_PEER_KEY}
  etcd-peer.pem: ${ETCD_PEER}
kind: Secret
metadata:
  name: etcd-server-peer-secret
  namespace: {{ .Values.namespace | default "erda-system" }}
type: Opaque
