apiVersion: v1
data:
  etcd-ca.pem: ${ETCD_CA}
  etcd-client-key.pem: ${ETCD_CLIENT_KEY}
  etcd-client.pem: ${ETCD_CLIENT}
kind: Secret
metadata:
  name: etcd-client-secret
  namespace: {{ .Values.global.namespace | default "erda-system" }}
type: Opaque
