# 全局可用参数
global:
  # 部署模式：支持最小化单点部署（demo） 和 高可用部署（prod） 两种模式
  size: prod
  # 组件部署的目标 namespace，如果不存在需要先创建
  namespace: default
  # 镜像参数
  image:
    # 镜像仓库
    repository: registry.erda.cloud/erda
    # 镜像拉取策略
    imagePullPolicy: IfNotPresent
  # 镜像拉取 Secrets
  imagePullSecrets: [ ]
  # 部署组件中 StatefulSet 负载使用的存储的 StorageClass 对象的名称
  storageClassName:

cassandra:
  # cassandra operator 实例名称
  operatorName: cassandra-operator
  # cassandra-operator 镜像 tag (版本)
  operatorVersion: v1.1.3-release
  # cassandra 节点实例名称
  name: addon-cassandra
  # addon-cassandra 镜像 tag (版本)
  version: 3.11.10
  # 高可用部署时 cassandra 节点数量
  replicas: 3
  # cassandra 节点存储容量
  capacity: 100Gi
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  # 机架列表，cassandra 部署时按机架分布以提高高可用性
  rack:
    # 每个 rack 的名称
    - name: rack1
    - name: rack2
    - name: rack3
