apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.redisOperator.name }}
  name: {{ .Values.redisOperator.name }}
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redisOperator.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      tolerations:
      - operator: Exists
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Values.redisOperator.name }}
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.redisOperator.name }}:{{ .Values.redisOperator.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: app
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      restartPolicy: Always