global:
  namespace: default
  size: demo
  image:
    repository: registry.erda.cloud/erda
    imagePullPolicy: IfNotPresent
  # Use this set to assign a list of default pullSecrets
  imagePullSecrets: [ ]
# TODO: storage class in global control or not
#  storageClass:
#    local: dice-local-volume
#    nfs: dice-nfs-volume

# TODO: add by lbl
expose:
   tls:
     # Enable the tls or not.
     enabled: true

# The persistence is enabled by default and a default StorageClass
# is needed in the k8s cluster to provision volumes dynamicly.
# Specify another StorageClass in the "storageClass" or set "existingClaim"
# if you have already existing persistent volumes to use
persistence:
  enabled: true
  # Setting it to "keep" to avoid removing PVCs during a helm delete
  # operation. Leaving it empty will delete PVCs after the chart deleted
  # (this does not apply for PVCs that are created for internal database
  # and redis components, i.e. they are never deleted automatically)
  resourcePolicy: "keep"
  persistentVolumeClaim:


# The update strategy for deployments: "RollingUpdate" or "Recreate"
# TODO：Set it as "Recreate" when "RWM" for volumes isn't supported
updateStrategy:
  type: RollingUpdate

# debug, info, warning, error or fatal
logLevel: info

# TODO: Support custom account password
# The initial password of Erda admin. Change it from portal after launching Harbor
adminPassword: "password12345"
# TODO: add by lbl

tags:
  work: false
  master: true

erda:
  clusterName: erda
  domain:
  masterClusterDomain:
  operator:
    name: erda-operator
    version: 1.0.0-20210427-3d25066
  image:
    repository: registry.erda.cloud/erda/
    imagePullPolicy: IfNotPresent
    components:
      init: init-image:1.0.0-20210510-21a3c66
      erda: erda:1.0.0-20210510-d7dd555
      erdaUI: erda-ui:1.0.0-20210508-f228247
      uc: erda-uc:1.0.0-20210425-d4c5a312
      telegraf: telegraf:1.0.0-20210510-dc02a9d
      analyzer:
        error: erda-analyzer-error-insight:1.0.0-20210422-69e9f84
        metrics: erda-analyzer-metrics:1.0.0-20210422-69e9f84
        alert: erda-analyzer-alert:1.0.0-20210422-69e9f84
      filebeat: filebeat:1.0.0-20210422-5b97371
      tmc: tmc:1.0.0-20210429-b87d98a
      soldier: soldier:1.0.0-20210426-daef74b
  clusterConfig:
    protocol: http
    ssh:
      user: root
      password: ""
    kubernetes:
      version:
      master:
      mastervip:
      lb:

volume-provisioner:
  name: volume-provisioner
  version: 1.0.0-20210416-1a3758f
  provisioner:
    local: dice/local-volume
    nfs: dice/netdata-volume
  storageclass:
    local: dice-local-volume
    nfs: dice-nfs-volume
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:

registry:
  name: addon-registry
  version: 2.7.1
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  storageClass: dice-local-volume
  networkMode: ""
  hostURL: ""
  hostNode:
  custom:
    address:

sonar:
  name: addon-sonar
  version: 8.4.2
  token: LY9DepZ7iDUsyH8TFoDR85ok7y2nw1
  password: 78tE846484lQQFUwY51h0Yr96ZQ063
  ingressHost: "sonar.erda.io"
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  custom:
    address:
    adminPassword:
    adminToken:

kms:
  version: 1.0.0-20200608-f11445f
  replicas: 1
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  etcdEndpoints: https://erda-etcd.erda-system.svc.cluster.local:2379


#nexus:
#  defaultAddress: https://maven.aliyun.com/repository/public
#  custom:
#    address:
#    username:
#    password:

redis:
  redisOperator:
    version: 1.0.0-20200723-1a7a9f14
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory:

  redisFailover:
    version: 3.2.12
    secret: aUVWSUk2TFk2RWJyYzRIWA==
    redis:
      replicas:
      resources:
        requests:
          cpu:
          memory:
        limits:
          cpu:
          memory:
    sentinel:
      replicas:
      resources:
        requests:
          cpu:
          memory:
        limits:
          cpu:
          memory:
  custom:
    masterName:
    password:
    sentinelsAddress:
