kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.sonar.name | default "addon-sonar" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      dice/addon: {{ .Values.sonar.name | default "addon-sonar" }}
  template:
    metadata:
      labels:
        dice/addon: {{ .Values.sonar.name | default "addon-sonar" }}
    spec:
      containers:
      - name: {{ .Values.sonar.name | default "addon-sonar" }}
        image:  {{ .Values.image.repository }}/{{ .Values.sonar.name | default "addon-sonar" }}:{{ .Values.sonar.version }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: SONAR_ADMIN_PASSWORD
          value: {{ .Values.sonar.password }}
        - name: SONAR_ADMIN_TOKEN
          value: {{ .Values.sonar.token }}
        - name: DICE_ADDON
          value: {{ .Values.sonar.name | default "addon-sonar" }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        resources:
          requests:
            cpu: {{ .Values.kms.resources.requests.cpu | default "0.1" | quote }}
            memory: {{ .Values.kms.resources.requests.memory | default "10Mi" | quote }}
          limits:
            cpu: {{ .Values.kms.resources.limits.cpu |  default "1.5" | quote }}
            memory: {{ .Values.kms.resources.limits.memory | default "3Gi" | quote }}
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 1
          timeoutSeconds: 10
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 9
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.nodematchExpressions }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                {{- range $_, $value := .Values.nodematchExpressions }}
                  - key: {{ $value.key }}
                    operator: {{ $value.operator }}
                {{- end }}
      {{- end }}
      tolerations:
      - operator: Exists
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 100%
