apiVersion: v1
kind: Service
metadata:
  labels:
    dice/addon: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  name: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    dice/addon: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    dice/addon: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  name: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}-master
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  ports:
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    dice/addon: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  sessionAffinity: None
  type: ClusterIP
