apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    dice/addon: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  name: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
secrets:
  - name: {{ .Values.elasticsearch.name | default "addon-elasticsearch" }}-token