apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dices.dice.terminus.io
spec:
  group: dice.terminus.io
  names:
    kind: Dice
    plural: dices
    singular: dice
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1beta1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Status
      type: string
      JSONPath: .status.phase
      description: Dice cluster current status
    - name: LastMessage
      type: string
      JSONPath: .status.conditions[0].reason
      description: last message