# 全局可用参数
global:
  # 部署模式：支持最小化单点部署（demo） 和 高可用部署（prod） 两种模式
  size: prod
  # 组件部署的目标 namespace，如果不存在需要先创建
  namespace: default
  # 镜像参数
  image:
    # 镜像仓库
    repository: registry.erda.cloud/erda
    # 镜像拉取策略
    imagePullPolicy: IfNotPresent
  # 镜像拉取 Secrets
  imagePullSecrets: [ ]
  # 部署组件中 StatefulSet 负载使用的存储的 StorageClass 对象的名称
  storageClassName:

mysql:
  # mysql 实例名称
  name: erda-mysql
  # mysql 镜像 tag (版本)
  version: 5.7.34
  # 数据库访问 用户名
  user: erda
  # 数据库访问 目标数据库
  database: erda
  # 数据库访问 密码
  password: password