apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nexus.name | default "addon-nexus" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
data:
  NEXUS_USERNAME: {{ .Values.nexus.username }}
  NEXUS_PASSWORD: {{ .Values.nexus.password }}