nexus:
  name: addon-nexus
  version: 3.29.1
  username: admin
  password: 02HLT5X0wb999sM0JuOOFrT9M3Bqjs
  ingressHost: nexus.${ERDA_GENERIC_DOMAIN}
  jvm:
    memory: "3072"
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory: