apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcd.name | default "erda-etcd" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  ports:
  - name: etcd-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: {{ .Values.etcd.name | default "erda-etcd" }}
