apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name | default "erda-mysql" }}
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
  - port: 3306
  selector:
    app: {{ .Values.mysql.name | default "erda-mysql" }}
