kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ .Values.cassandraOperator.name | default "cassandra-operator" }}
  name: {{ .Values.cassandraOperator.name | default "cassandra-operator" }}
  namespace: {{ .Values.global.namespace | default "erda-system"}}
rules:
- apiGroups:
  - db.orange.com
  resources:
  - "cassandraclusters"
  - "cassandrabackups"
  - "cassandrarestores"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
    - db.orange.com
  resources:
    - cassandraclusters/status
    - cassandrabackups/status
    - cassandrarestores/status
  verbs:
    - get
    - update
    - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ .Values.cassandraOperator.name | default "cassandra-operator" }}
  name: cassandra-cluster-node
  namespace: {{ .Values.global.namespace | default "erda-system"}}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets" ]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get","create"]
