apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.cassandraOperator.name | default "cassandra-operator" }}
  name: {{ .Values.cassandraOperator.name | default "cassandra-operator" }}
  namespace: {{ .Values.global.namespace | default "erda-system" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.cassandraOperator.name | default "cassandra-operator" }}
  name: cassandra-cluster-node
  namespace: {{ .Values.global.namespace | default "erda-system" }}

