apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sonar.name | default "addon-sonar" }}
  namespace: {{ .Values.namespace | default "erda-system" }}
data:
  SONAR_ADMIN_PASSWORD: {{ .Values.sonar.password }}
  SONAR_ADMIN_TOKEN: {{ .Values.sonar.token }}
