apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-operator
  name: redis-operator
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      tolerations:
        - operator: Exists
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: redis-operator
      containers:
        - image: {{ .Values.global.image.repository }}/redis-pperator:{{ .Values.redisOperator.version }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
          name: app
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
      restartPolicy: Always