global:
  size: demo
  namespace: default
  image:
    repository: registry.erda.cloud/erda
    imagePullPolicy: IfNotPresent
  imagePullSecrets: [ ]

name: addon-registry
version: 2.7.1
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
storageClass: dice-local-volume
networkMode: ""
hostURL: ""
hostNode:

