apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-operator
  name: redis-operator
  namespace: {{ .Values.namespace | default "erda-system" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: redis-operator
      containers:
      - image: {{ .Values.image.repository }}/redis-operator:1.0.0-20200723-1a7a9f14
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: app
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      restartPolicy: Always