global:
  size: demo
  namespace: default
  image:
    repository: registry.erda.cloud/erda
    imagePullPolicy: IfNotPresent
  imagePullSecrets: [ ]

redisOperator:
  version: 1.0.0-20200723-1a7a9f14
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:

redisFailover:
  version: 3.2.12
  secret: aUVWSUk2TFk2RWJyYzRIWA==
  redis:
    replicas:
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory:
  sentinel:
    replicas:
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory: