global:
  size: demo
  namespace: default
  image:
    repository: registry.erda.cloud/erda
    imagePullPolicy: IfNotPresent
  imagePullSecrets: [ ]

name: volume-provisioner
version: 1.0.0-20210416-1a3758f
provisioner:
  local: dice/local-volume
  nfs: dice/netdata-volume
storageclass:
  local: dice-local-volume
  nfs: dice-nfs-volume
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory: