apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pv-claim
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  storageClassName: {{ .Values.storageclass.local | default "erda-local-volume" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
